### ISSUE TITLE
SBCL on Windows isn't built with `--with-sb-core-compression`

### ISSUE THREAD

**Issue by simendsjo** [roswell/sbcl_bin#10]
This makes the images quite big on Windows. I know it's not enabled by default, but maybe include an installer with the feature enabled if it's a simple fix?

EDIT: A previous issue indicates compression has been in at least some previous builds: https://github.com/roswell/sbcl_bin/issues/3

**Comment by snmsts** [comment]
from 2.4.9 I could static link libzstd and core-compression feature is turned on.
