### ISSUE TITLE
sbcl 1.4.10 no darwin binary release

### ISSUE THREAD

**Issue by t-cool** [roswell/sbcl_bin#2]
$ ros run
Installing sbcl-bin...
No SBCL version specified. Downloading platform-table.html to see the available versions...
[##########################################################################]100%
Installing sbcl-bin/1.4.10...
Downloading https://github.com/roswell/sbcl_bin/releases/download/1.4.10/sbcl-1.4.10-x86-64-darwin-binary.tar.bz2
Download Failed with status 2. See download_simple in src/download.c
ros: warning: ros crashed, killed by SIGSEGV.
ros itself has not crashed, but for transparency,
it will now kill itself (without dumping core) with the same signal

warnings can be silenced by the --no-warnings (-n) option
Segmentation fault: 11

**Comment by snmsts** [comment]
same as #1
