### ISSUE TITLE
SBCL 2.0.0 for Windows contains no zlib1.dll

### ISSUE THREAD

**Issue by phoe** [roswell/sbcl_bin#3]
[The MSI installer for SBCL 2.0.0 from Roswell releases](https://github.com/roswell/sbcl_bin/releases/download/2.0.0/sbcl-2.0.0-x86-64-windows-binary.msi) doesn't contain `zlib1.dll` even though the SBCL binary contained in there is built with core compression feature.

This means that the SBCL installed from that MSI file doesn't work unless there is a system-wide installed zlib1.dll available.

**Comment by snmsts** [comment]
ah...

**Comment by snmsts** [comment]
fixed.
