### ISSUE TITLE
There is no freebsd sbcl_bin release since 1.27.

### ISSUE THREAD

**Issue by fgatherlet** [roswell/sbcl_bin#4]
Hi.

Can you release freebsd sbcl_bin constantly?

Surely I can install and use sbcl/2.0.1, but roswell's some script seems to use default sbcl_bin.
So it often causes some troubles.

For example, `ros install static-vectors` launches not sbcl but default sbcl_bin.
And old sbcl binary often cannot compile new quicklisp packages...

**Comment by snmsts** [comment]
I don't have freebsd box.. do you have idea how to?

**Comment by snmsts** [comment]
```
ros sbcl-bin.version=system setup
```

could be helpful.

**Comment by fgatherlet** [comment]
Thanks for your replying.

`ros sbcl-bin.version=system setup` did not resolve the problem.

The problem seems to be...
`cffi_0.20.1/toolchain/bundle.lisp` uses `uiop:os-cond`.
But sbcl-bin/1.2.7 (or bundled asdf) does not have `uiop:os-cond`.
etc.etc..

I have decided to adopt an ugly-but-working solution.

```
$ cp -r ~/.roswell/impls/x86-64/freebsd/sbcl/2.0.1 ~/.roswell/impls/x86-64/freebsd/sbcl-bin/
$ ros use sbcl-bin/2.0.1
```

**Comment by snmsts** [comment]
I manually put 2.1.2 https://github.com/roswell/sbcl_bin/releases/download/2.1.2/sbcl-2.1.2-x86-64-freebsd-binary.tar.bz2.
hope it's working.
