### ISSUE TITLE
No Windows build since 2.0.2

### ISSUE THREAD

**Issue by lockie** [roswell/sbcl_bin#6]
There seems to be the error preventing Windows msi build: https://travis-ci.org/github/roswell/sbcl_bin/jobs/703283976

**Comment by phoe** [comment]
> which: no sudo in (/c/Users/travis/.roswell/bin:/c/Users/travis/.roswell/bin:/bin:/usr/bin:/c/tools/ruby27/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/ProgramData/GooGet:/c/Program Files/Google/Compute Engine/metadata_scripts:/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin:/c/Program Files/Google/Compute Engine/sysprep:/c/Program Files/Docker:/c/ProgramData/chocolatey/bin:/c/Program Files/CMake/bin:/c/Program Files/Git/cmd:/c/Program Files/LLVM/bin:/c/Program Files/dotnet:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/tools/BCURRAN3:/c/Users/travis/AppData/Local/Microsoft/WindowsApps:/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin)

Seems like it attempts to find sudo and fails. It shouldn't be using sudo, methinks, it's on windows where builds run as administrator... but then again, I'm not a Windows specialist.

**Comment by lockie** [comment]
As it turns out, the problem was not in `sudo` (although the script errors about `sudo`, it limps further), but rather in the `PATH` setting.

**Comment by snmsts** [comment]
I think it solved.
