### ISSUE TITLE
Mac ARM builds

### ISSUE THREAD

**Issue by EthanYidong** [roswell/sbcl_bin#7]
We have arm builds for linux, and we have builds for x86_64 Macs, so it shouldn't be too hard(?) to add builds for M1 Macs.

**Comment by snmsts** [comment]
I don't understand what's your context... do you check sbcl-devel?

**Comment by EthanYidong** [comment]
Oh. I'm so sorry, I was under the impression that SBCL was working natively, but I forgot that I installed it under the x86_64 rosetta emulated homebrew. My bad.

**Comment by snmsts** [comment]
my understanding is it's about to release status.
