### ISSUE TITLE
FreeBSD sbcl-bin is built without SB_THREAD

### ISSUE THREAD

**Issue by dmgk** [roswell/sbcl_bin#9]
sbcl-bin that is downloaded by ros during initial install is built without SB-THREAD. That creates problems with FASL incompatibility if user later also decides to `ros install sbcl`, which is built from source and has SB-THREAD. Both sbcl-bin and sbcl use the same cache directory (~/.cache/common-lisp/sbcl-2.2.4-bsd-x64 for the current version) and their generated FASLs are incompatible between these two versions.

Could you please update build options for the FreeBSD version of sbcl-bin to include SB-THREAD?

**Comment by snmsts** [comment]
uploaded 2.2.4

**Comment by dmgk** [comment]
Thanks!

**Comment by ak-coram** [comment]
@snmsts: I think this issue might be reoccurring with 2.3.5 (can't load `bordeaux-threads: This implementation is unsupported.`)
